[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pycas"
version = "0.1.0"
description = "A minimal symbolic calculus engine"
requires-python = ">=3.9"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["pycas"]